cfg = mfatConfig();

% Optional overrides
cfg.entropy.enabled = true;
cfg.entropy.beta = 0.4;

cfg.fractional.enabled = true;
cfg.fractional.alpha = 0.8;

mfatValidateConfig(cfg);

% --- MFAT-λ ---
R_lambda = mfatLambda(I, sigmas, ...
    'tau',cfg.core.tau, ...
    'tau2',cfg.core.tau2, ...
    'D',cfg.core.D, ...
    'whiteOnDark',cfg.core.whiteOnDark, ...
    'precision',cfg.core.precision);

% --- MFAT-Prob ---
if cfg.prob.enabled
    P = mfatProb(I, sigmas, ...
        'tau',cfg.core.tau, ...
        'tau2',cfg.core.tau2, ...
        'D',cfg.core.D, ...
        'whiteOnDark',cfg.core.whiteOnDark, ...
        'precision',cfg.core.precision);
end

if cfg.entropy.enabled
    faStack = zeros([size(I), numel(sigmas)], cfg.core.precision);
    for k = 1:numel(sigmas)
        geom = mfatCore2D(I, sigmas(k), cfg.core);
        faStack(:,:,k) = geom.fa;
    end

    R_lambda = mfatEntropyWeight( ...
        R_lambda, faStack, ...
        'beta',cfg.entropy.beta, ...
        'combine',cfg.entropy.combine);
end

if cfg.fractional.enabled
    R_lambda = mfatFractional( ...
        R_lambda, ...
        'alpha',cfg.fractional.alpha);
end
